# Global Constants
SETTINGS_PATH = 'settings.json'
FIREBASE_CONF_PATH = 'isolinna.json'
TOKEN_UPDATE_DURATION = 1800    # 1800 seconds = 30 minutes

LOGIN_SCREEN_WIDTH = 0
LOGIN_SCREEN_HEIGHT = 12
MAIN_SCREEN_WIDTH = 0
MAIN_SCREEN_HEIGHT = 12 
MAIN_MENU_WIDTH = 22
MAIN_MENU_HEIGHT = 9
SETTINGS_MENU_WIDTH = 28
SETTINGS_MENU_HEIGHT = 7
SENSORS_MENU_WIDTH = 29
SENSORS_MENU_HEIGHT = 10
TIME_INTERVAL_DIALOG_WIDTH = 40
TIME_INTERVAL_DIALOG_HEIGHT = 8
UUID_DIALOG_WIDTH = 58
UUID_DIALOG_HEIGHT = 8
SENSORS_DIALOG_WIDTH = 60
SENSORS_DIALOG_HEIGHT = 15